name: Tests
"on":
  pull_request: {}
  push:
    branches:
    - main
jobs:
  unit:
    name: Unit Test
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITH: development
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Run Tests
      run: bundle exec rake
    - uses: codecov/codecov-action@v5
